# TensorFlow
Introduccion.

In [0]:
import numpy as np
import tensorflow as tf

In [4]:
tf.__version__

'2.2.0-rc2'

## Constantes

### Definicion de constantes
* Entender como crear variables constantes
* La principal ventaja comparada con TF1.X es la comodidad que se puede obtener con la integracion de numpy
* Los objetos de tensorflow requieren arrays

In [5]:
tensor = tf.constant([[20,4] ,[32,52]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  4],
       [32, 52]], dtype=int32)>

In [7]:
#se puede ver los atributos tambien de un tensor
print(tensor.shape)
print(tensor.dtype)
print(tensor.numpy())

(2, 2)
<dtype: 'int32'>
[[20  4]
 [32 52]]


In [8]:
numpy_tensor = np.array([[25,4],[21,54]])
tensor_from_np = tf.constant(numpy_tensor)
tensor_from_np

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[25,  4],
       [21, 54]])>

## Variables

### Definicion de variables
* Se declaran con la clase `Variable`
* Se utilizan los mismos metodos para ver sus atributos
* La diferencia entre constantes y variables, es que la primera se mantiene igual en todo el modelo mientras el segundo puede ir variando

In [9]:
variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### Cambiar la configuracion

Se puede modificar los valores e incluso obtenerlos igual que un arreglo comun y corriente

In [12]:
variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operacion con los tensores
* Al estar utilizando una matriz, se aplica suma escalar y multiplicacion escalar.
  * Basicamente es hacer un calculo a todos los elementos
  * Esto nos permite hacer calculos de algebra lineal
* La integracion con numpy es tal que nos permite aplicar todas los calculos que haciamos en numpy a nuestros tensores

In [15]:
tensor.numpy()

array([[20,  4],
       [32, 52]], dtype=int32)

In [13]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22,  6],
       [34, 54]], dtype=int32)>

In [14]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  20],
       [160, 260]], dtype=int32)>

In [16]:
#Esto esta aplicando una multiplicacion por fila
tensor * [1,2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 20,   8],
       [ 32, 104]], dtype=int32)>

In [18]:
print('obtener la raiz cuadrada: ',np.sqrt(tensor))
print('obtener el promedio: ',np.mean(tensor))
print('Obtener el cuadrado: ',np.square(tensor))

obtener la raiz cuadrada:  [[4.47213595 2.        ]
 [5.65685425 7.21110255]]
obtener el promedio:  27.0
Obtener el cuadrado:  [[ 400   16]
 [1024 2704]]


### Producto escalar entre tensor o producto tensorial
* Con esta hay que tener cuidado con esto, porque no es multiplicacion de tensor1 * tensor2 sino que es un producto escalar
* En otras palabras se aplica un producto matricial

In [24]:
tensor1 = tf.constant([[2,4],[2,4]])
tensor2 = tf.constant([[1,3],[1,3]])
tensor3 = np.dot(tensor1,tensor2)
print('Tensor 1: \n',tensor1.numpy())
print('Tensor 2: \n',tensor2.numpy())
print('Tensor 3: \n',tensor3)

Tensor 1: 
 [[2 4]
 [2 4]]
Tensor 2: 
 [[1 3]
 [1 3]]
Tensor 3: 
 [[ 6 18]
 [ 6 18]]


## String en TensorFlow

In [26]:
tensor_str = tf.constant('TensorFlow')
tensor_str

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

### Operaciones tipicas

In [27]:
tf.strings.length(tensor_str)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [28]:
# codifiacion y decodificacion
tf.strings.unicode_decode(tensor_str , 'UTF8')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Almacenar arrays de strings

In [0]:
tf_str_array = tf.constant(['TensorFlow','IA','Machine Learning'])

In [30]:
for string in tf_str_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'IA', shape=(), dtype=string)
tf.Tensor(b'Machine Learning', shape=(), dtype=string)
